import '../css/app.css';
import './bootstrap';
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/500.css";
import "@fontsource/poppins/600.css";
import "@fontsource/poppins/700.css";

import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { createApp, h } from 'vue';
import VueTailwindDatepicker from "vue-tailwind-datepicker";
import { ZiggyVue } from '../../vendor/tightenco/ziggy';
import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { faSearchengin } from "@fortawesome/free-brands-svg-icons";
import {
    faAngleLeft,
    faAngleUp,
    faAngleDown,
    faArrowTrendUp,
    faArrowTrendDown,
    faBan,
    faBars,
    faBarsStaggered,
    faMoneyBillTrendUp,
    faBook,
    faBookBookmark,
    faBuilding,
    faBuildingCircleCheck,
    faCheck,
    faChartPie,
    faChartLine,
    faCheckDouble,
    faChevronLeft,
    faChevronUp,
    faChevronDown,
    faCircle,
    faCircleChevronLeft,
    faCircleDown,
    faCircleXmark,
    faComputer,
    faCoins,
    faCopy,
    faDiagramSuccessor,
    faDiceD6,
    faDisplay,
    faEye,
    faEyeSlash,
    faFile,
    faFileCircleQuestion,
    faFlagCheckered,
    faGraduationCap,
    faHome,
    faIndustry,
    faHourglassHalf,
    faKey,
    faList,
    faListOl,
    faLock,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMeteor,
    faMicrochip,
    faPaperPlane,
    faPercent,
    faPen,
    faPenNib,
    faPencil,
    faPlus,
    faPlusCircle,
    faRecycle,
    faRightToBracket,
    faRotateLeft,
    faRotateRight,
    faSave,
    faScrewdriverWrench,
    faServer,
    faSignOutAlt,
    faSort,
    faSquarePen,
    faStar,
    faSunPlantWilt,
    faTable,
    faTachometerAlt,
    faTags,
    faThList,
    faTrashCan,
    faUser,
    faUserTie,
    faUsers,
    faXmark
} from "@fortawesome/free-solid-svg-icons";
library.add(
    faAngleLeft,
    faAngleUp,
    faAngleDown,
    faArrowTrendUp,
    faArrowTrendDown,
    faBan,
    faBars,
    faBarsStaggered,
    faMoneyBillTrendUp,
    faBook,
    faBookBookmark,
    faBuilding,
    faBuildingCircleCheck,
    faCheck,
    faChartPie,
    faChartLine,
    faCheckDouble,
    faChevronLeft,
    faChevronUp,
    faChevronDown,
    faCircle,
    faCircleChevronLeft,
    faCircleDown,
    faCircleXmark,
    faComputer,
    faCoins,
    faCopy,
    faDiagramSuccessor,
    faDiceD6,
    faDisplay,
    faEye,
    faEyeSlash,
    faFile,
    faFileCircleQuestion,
    faFlagCheckered,
    faGraduationCap,
    faHome,
    faIndustry,
    faHourglassHalf,
    faKey,
    faList,
    faListOl,
    faLock,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMeteor,
    faMicrochip,
    faPaperPlane,
    faPercent,
    faPen,
    faPenNib,
    faPencil,
    faPlus,
    faPlusCircle,
    faRecycle,
    faRightToBracket,
    faRotateLeft,
    faRotateRight,
    faSave,
    faScrewdriverWrench,
    faServer,
    faSignOutAlt,
    faSort,
    faSquarePen,
    faStar,
    faSunPlantWilt,
    faSearchengin,
    faTable,
    faTachometerAlt,
    faTags,
    faThList,
    faTrashCan,
    faUser,
    faUserTie,
    faUsers, 
    faXmark
);
config.autoAddCss = false;
const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob('./Pages/**/*.vue'),
        ),
    setup({ el, App, props, plugin }) {
        const vueApp = createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(VueTailwindDatepicker)
            .component("font-awesome-icon", FontAwesomeIcon)
        return vueApp.mount(el)
    },
    progress: {
        color: "#8B1E3F",
        showSpinner: true,
        delay: 250,
    },
});
